package unii.entertainment.teammaker.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import unii.entertainment.teammaker.db.Category;
import unii.entertainment.teammaker.db.Player;

import unii.entertainment.teammaker.db.CategoryDao;
import unii.entertainment.teammaker.db.PlayerDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig categoryDaoConfig;
    private final DaoConfig playerDaoConfig;

    private final CategoryDao categoryDao;
    private final PlayerDao playerDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        categoryDaoConfig = daoConfigMap.get(CategoryDao.class).clone();
        categoryDaoConfig.initIdentityScope(type);

        playerDaoConfig = daoConfigMap.get(PlayerDao.class).clone();
        playerDaoConfig.initIdentityScope(type);

        categoryDao = new CategoryDao(categoryDaoConfig, this);
        playerDao = new PlayerDao(playerDaoConfig, this);

        registerDao(Category.class, categoryDao);
        registerDao(Player.class, playerDao);
    }
    
    public void clear() {
        categoryDaoConfig.clearIdentityScope();
        playerDaoConfig.clearIdentityScope();
    }

    public CategoryDao getCategoryDao() {
        return categoryDao;
    }

    public PlayerDao getPlayerDao() {
        return playerDao;
    }

}
